<!DOCTYPE html>
<html lang=ru"">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>Ошибка 404</title>
    <link href="/css/404.css" rel="stylesheet">
    <link href="/css/errorNotFound.css" rel="stylesheet">
    <link rel="icon" type="image/ico" href="https://itvdn.com/Content/img/common/favicon.ico">

    <style type="text/css">#AF_kph0, #AF_kph1, #BlWrapper > .b-temp_rbc, #JobInformer, #MT_overroll ~ div[class][style="left:0px;top:0px;height:480px;width:650px;"], #PopWin[onmousemove], #SR_PopOver, #SR_PopOverModalBackground, #ad_ph_2, #ad_ph_3, #ad_ph_4, #ad_ph_8, #addsDiv, #adv_kod_frame, #adv_kod_frame ~ #gotimer, #adv_unisound ~ #ad_module_cont > [id^="ad_module"], #adv_unisound ~ #main > #slidercontentContainer, #advideo_adv, #advideo_adv_main_div, #advm_preload, #cyberinfrm_18, #eropromo_icq, #export_test_inboobs, #fp_adv, #fp_banner, #gaminator, #girlsBar, #h_24x4, #index > .news_not_adv, #limonads_body, #logethy_iframe, #magnaInformer, #marketgid, #mmmBanner, #nor_wrap, #novem_billboard, #radeant, #vid_vpaut_div, #winvideoPlayer, #zhlobam_net_informer_console, .MIXADVERT_NET, .SC_TBlock, .ad-240x400, .ad-richmedia, .ad-richmedia-overlay, .admachina-banner, .ads300-thumb, .ads600x200, .ads_600x200, .adsbyyottos {
            display: none !important;
        }

        a[href*="//loderls.ru"], a[href*="//loderlx.ru"], a[href*="//loderna.ru"], a[href*="//parandeya.com/"], a[href*="//portakamus.com/"], a[href*="//refpaewsbc.top/"], a[href*="//reruniversal.com/"], a[href*="//restofarian.com"], a[href*="//tiruniversal.com/"], a[href*="//ubar-pro"], a[href*="//ubar.pro"], a[href*="//universalice.info/"], a[href*="//universalie.info/"], a[href*="//universalies.info/"], a[href*="//universalin.info/"], a[href*="//universalini.info/"], a[href*="//universalse.info/"], a[href*="//universalut.info/"], a[href*="//utimg.ru/"], a[href*="//viruniversal.com/"], a[href*="//webbrowser.club/"], a[href*="//yojlf.com"], a[href*="/advertisesimple.info"], a[href*="/advjump.com"], a[href*="/afftraf.co/"], a[href*="/amigo-browser.ru"][target="_blank"], a[href*="/api/redirect?offerid="], a[href*="/ber-ter.com"], a[href*="/clubleads.ru"], a[href*="/eversaree.bid"], a[href*="/fastvk.com"], a[href*="/get-torrent.ru"], a[href*="/getdriverpack.ru"], a[href*="/installpack.net"], a[href*="/kshop3.biz"], a[href*="/loaderu.ru/"], a[href*="/mosday.ru/ad/"], a[href*="/myuniversalnk.com/"], a[href*="/myuniversalnk.net/"], a[href*="/newbrowser.club/"], a[href*="/ogclick.com/api/redirect"], a[href*="/onvix.co/promo/"][target=_blank], a[href*="/onvix.me/promo/"][target=_blank], a[href*="/onvix.tv/promo/"][target=_blank], a[href*="/ribnadzo.ru"], a[href*="/rlink/simptizer/"], a[href*="/sarimsolus.com/"], a[href*="/u-load.ru/"], a[href*="/u-loads.ru/"], a[href*="/uloads.ru/"] {
            display: none !important;
        }

        a[href*="/uni-lnk.com/"], a[href*="/universal-lnk.net/"], a[href*="/universallnk.net/"], a[href*="/universalsrc.com/"], a[href*="/universalsrc.net/"], a[href*="/vkout.ru"], a[href*="/yfiles1.ru"], a[href*="://adv-views.com"], a[href*="://analyticsq.com"], a[href*="://bubblevard.com/"], a[href*="://chikidiki.ru"], a[href*="://clickstats.online/"], a[href*="://clickstats.pw/"], a[href*="://et-cod.com/"], a[href*="://etcodes.com/"], a[href*="://getbrauzer.ru/"], a[href*="://loderkkis.ru"], a[href*="://new.torrent-pack.ru/"], a[href*="://ourbrowser.net"], a[href*="://parandaya.com"], a[href*="://renderbrandium.com"], a[href*="://rendersaveron.com"], a[href*="://segodnia.club/"], a[href*="://sub"][href*="bubblesmedia.ru"], a[href*="://vpnbrowser.ru/"], a[href*="admitlead."][href*="/sb/clk/"], a[href*="ads-provider.com"], a[href*="ads2-adnow.com"], a[href*="advertwebgid.ru"], a[href*="amgfile.ru"], a[href*="amigo-biz.ru/ads/click"], a[href*="awesomeredirector"], a[href*="beauty-list.ru"], a[href*="best-zdorovye.ru"], a[href*="best-zdrav.ru"], a[href*="bestforexplmdb.com"], a[href*="beststbuy.ru"], a[href*="bgrndi.com"], a[href*="blogers-story.ru"], a[href*="blogi-novosti.ru"], a[href*="browser-ru.site"], a[href*="bubblesmedia.ru/sb/clk/"], a[href*="cmsmodnews.com"], a[href*="cpagetti1.com"], a[href*="cpl1.ru"], a[href*="cpl11.ru"], a[href*="down-news-games.ru"], a[href*="ex.24smi.info"], a[href*="feellights.ru"], a[href*="filebase.me"] {
            display: none !important;
        }

        a[href*="films.ws"], a[href*="flylinks.pw"], a[href*="fortedrow.pro"], a[href*="ftpglst.com"], a[href*="go.ad2up.com"], a[href*="gocdn.ru"], a[href*="goext.info"], a[href*="goodtrack.ru"], a[href*="gpclick.ru"], a[href*="herrabjec.pro"], a[href*="https://relap.io/r?"], a[href*="idealmedia.io"], a[href*="info-blog24.ru"], a[href*="intovarro.ru"], a[href*="joycasino.com/?partner="], a[href*="katuhus.com"], a[href*="kingoablc.com"], a[href*="kinqon.ru"], a[href*="kma1.biz"], a[href*="kodielinktrust.ru"], a[href*="kshop2.biz"], a[href*="land-gooods.ru"], a[href*="lifebloggersz.ru"], a[href*="lifenews24x7.ru"], a[href*="linkmyc.com"], a[href*="litewebbusiness.com"], a[href*="m1cpl.ru"], a[href*="marketgid.com/"], a[href*="media-rotate.com"], a[href*="medicalblogs.ru"], a[href*="medinforms.ru"], a[href*="mixadvert.com"], a[href*="muz-loader.site"], a[href*="navaxudoru.com"], a[href*="netcrys.com"], a[href*="nhebd.xyz"], a[href*="octoclick.net"], a[href*="offhealth.ru"], a[href*="please-direct.com"], a[href*="please-direct.me"], a[href*="problogrus.ru"], a[href*="rapidtor.ru/sb/clk/"], a[href*="re-directme.com"], a[href*="realgoodies.ru"], a[href*="refpazus.top"], a[href*="retagapp.com"], a[href*="rexchange.begun.ru/rclick?"], a[href*="sandratand.ru"], a[href*="sapmedia.ru"], a[href*="shakes.pro"] {
            display: none !important;
        }

        a[href*="shakescash.com"], a[href*="shakesclick.com"], a[href*="shakesin.com"], a[href*="shakespoint.com"], a[href*="slovosil.com"], a[href*="sviruniversal.com/"], a[href*="tdstrk.ru"], a[href*="thor-media.ru/click/"], a[href*="top-info24.ru"], a[href*="top.24smi.info"], a[href*="torrentum.ru"], a[href*="tptrk.ru"], a[href*="trafgid.xyz"], a[href*="traflabs.xyz"], a[href*="trk-1.com"], a[href*="trklp.ru"], a[href*="trtkp.ru"], a[href*="turbotraf.com"], a[href*="tvks.ru"], a[href*="tvkw.ru"], a[href*="tvroff.net"], a[href*="twtn.ru/"], a[href*="ultrabit.ws"], a[href*="verismediya.ru/sb/clk/"], a[href*="webdiana.ru/click"], a[href*="wow-partners.com/click.php"], a[href*="zdravo-med.ru"], a[href="http://advert.mirtesen.ru/"], a[href^="http://amigodistr.ru/"], a[href^="http://amigodistrib.ru/dkit-hps/"], a[href^="http://apytrc.com/click/"], a[href^="http://browserload.info/"], a[href^="http://datxxx.com"], a[href^="http://eaplay.ru/"], a[href^="http://fly-shops.ru"], a[href^="http://glprt.ru/affiliate/"], a[href^="http://kshop.biz/"], a[href^="http://luckiestclick.com/goto."], a[href^="http://olivka.biz/"], a[href^="http://putanapartners.com/go."], a[href^="http://reals-story.ru/"], a[href^="http://tds-2.ru"], a[href^="http://traderstart.mirtesen.ru"], a[href^="http://trafmaster.com"], a[href^="https://bongacams"][href*="com/track?"], a[href^="https://homyanus.com"], a[href^="https://kshop"][href*=".pro/"], a[href^="https://msetup.pro"], a[href^="https://relap.io/"][href*="promo_ad_link"], a[href^="https://www.juicer.io?referrer="] {
            display: none !important;
        }

        a[onclick*="//msetup.pro/"], a[onclick*="/link-fes.ru"], a[onclick*="n284adserv.com"], a[onclick*="offergate-amigo"], a[onclick*="trtkp.ru"], div[class*="relap"][class*="-rec-item"], div[class*="spklw"][data-type="ad"], div[class^="block_fortress"], div[class^="da-widget-"], div[class^="da-ya-widget"], div[class^="mixadvert"], div[data-id^="div-gpt-ad-"], div[id*="Teaser_Block"], div[id^="CGCandy"], div[id^="Crt-"][style], div[id^="DIV_DA_"], div[id^="M"][id*="Composite"], div[id^="admixer_"], div[id^="adpartner-jsunit-"], div[id^="ads_games_"], div[id^="advertur_"], div[id^="b_tz_"], div[id^="beroll_rotator"], div[id^="cpa_rotator_block"], div[id^="criteo-"][style], div[id^="gnezdo_ru_"], div[id^="join_informer_"], div[id^="news_2xclick_ru_"], div[id^="news_nest_msk_ru"], div[id^="news_nest_net_ru"], div[id^="republer_"], div[id^="rtn4p"], div[id^="sblock_inform_"], div[id^="smi2adblock_"], div[id^="tizerws_"], div[id^="traffim-widget"], div[id^="trafmag_"], div[id^="zcbclk"], div[style*="am15.net/img/player_skins"], iframe[id^="republer"], iframe[src*="/3647.tech"], iframe[src*="/mixadv_"], iframe[src*="://vidroll.ru/"], iframe[src*="ads.exosrv.com"], iframe[src*="laim.tv/rotator/"], iframe[src*="marketgid.com"], iframe[src*="traffic-media.co"], iframe[src*="trafic-media.ru"], iframe[src*="utraff.com"], img[width="120"][height="600"] {
            display: none !important;
        }

        img[width="160"][height="600"], noindex > .search_result[class*="search_result_"], object[data*="ads.com/clk.swf"], object[data^="blob"], .a-buttons.blue-but.a-check, .a-buttons.green-but.a-clock, div[style="width: 252px; height: 450px; position: fixed; right: 0px; top: 0px; overflow: hidden; z-index: 10000;"], #pgeldiz, #root > .app > #layout > #very-right-column .aggregator__header, .app.blog-post-page #blog-post-item-video-ad, .app.blog-post-page .secondary-header-ad-block, body > #__promoStickyButton, .jtn-widget-adv, .widget-autoru, .rbcobmen, #banner.b-banner__content, .b-spec-adv, .b-yabrowser-promo, .content__right > .z-market_right_yes, .i-bem.adsrv, .i-bem.b-timetable__row[onclick*="awaps"], .i-bem.stripe_type_promo, .i-bem.tv-grid__item-adv, .i-bem.tv-sortable-item.tv-sortable-item_sortable_no, .spec-adv, .stat_pixel_yes[onclick][class*="_layout_"][class*="_format_"], .yandex-rtb, .yandex-rtb-block, div[id^="yandex_rtb"], #_u_ablock_bottomlink, #_u_ablock_toplink, #u_preroll_overlay, #u_preroll_videoadbetnet, #u_preroll_videoinvi, #u_preroll_videomvd, a[href*="/ulike.farm"], body > div[id^="dV"][style^="width"][style*="height"][style*="position"][style*="fixed"][style*="overflow"][style*="z-index"][style*="background"], body > iframe[style^="position"][style*="fixed"][id^="iFb"][src^="/?"], body > div[class^="_"][class*="Notification "][class$="Notification_stBig"], .min-width-normal > #popup_container, .min-width-normal > #popup_container ~ #fade, embed[height="175"][width="175"], embed[height="200"][width="100%"], embed[height="200"][width="175"], embed[height="233"][width="280"], embed[height="250"][width="175"], embed[width="100%"][height="100"], embed[width="1000"][height="150"], embed[width="120"][height="240"], embed[width="120"][height="600"] {
            display: none !important;
        }

        embed[width="160"][height="600"], embed[width="180"][height="300"], embed[width="180"][height="530"], embed[width="200"][height="230"], embed[width="200"][height="250"], embed[width="200"][height="300"], embed[width="200"][height="400"], embed[width="200"][height="500"], embed[width="210"][height="270"], embed[width="212"][height="300"], embed[width="215"][height="359"], embed[width="220"][height="250"], embed[width="240"][height="150"], embed[width="240"][height="250"], embed[width="240"][height="300"], embed[width="240"][height="400"], embed[width="240"][height="420"], embed[width="250"][height="250"], embed[width="300"][height="250"], embed[width="310"][height="70"], embed[width="430"][height="120"], embed[width="460"][height="70"], embed[width="468"][height="60"], embed[width="470"][height="50"], embed[width="500"][height="100"], embed[width="500"][height="120"], embed[width="500"][height="170"], embed[width="570"][height="100"], embed[width="600"][height="160"], embed[width="600"][height="200"], embed[width="600"][height="90"], embed[width="680"][height="130"], embed[width="700"][height="60"], embed[width="728"][height="90"], embed[width="940"][height="90"], embed[width="960"][height="120"], iframe[width="104"][height="464"], iframe[width="200"][height="300"], iframe[width="210"][height="237"], iframe[width="240"][height="350"], iframe[width="468"][height="60"], iframe[width="780"][height="120"], iframe[width="980"][height="90"], img[width="460"][height="60"], img[width="600"][height="90"], img[width="720"][height="90"], object[height="100"][width="550"], object[height="120"][width="120"], object[height="175"][width="175"], object[height="200"][width="100%"] {
            display: none !important;
        }

        object[height="250"][width="175"], object[height="380"][width="190"], object[height="80"][width="100%"], object[height="97"][width="500"], object[width="100%"][height="150"], object[width="100%"][height="250"], object[width="100%"][height="60"], object[width="100%"][height="90"], object[width="1000"][height="100"], object[width="1000"][height="150"], object[width="1000"][height="200"], object[width="1000"][height="300"], object[width="1000"][height="70"], object[width="1000"][height="90"], object[width="1020"][height="200"], object[width="1020"][height="220"], object[width="1024"][height="150"], object[width="1024"][height="80"], object[width="120"][height="300"], object[width="120"][height="60"], object[width="120"][height="600"], object[width="140"][height="320"], object[width="140"][height="600"], object[width="1440"][height="299"], object[width="150"][height="150"], object[width="150"][height="250"], object[width="150"][height="300"], object[width="150"][height="360"], object[width="160"][height="200"], object[width="160"][height="400"], object[width="160"][height="600"], object[width="161"][height="250"], object[width="170"][height="170"], object[width="170"][height="80"], object[width="175"][height="200"], object[width="175"][height="220"], object[width="180"][height="107"], object[width="180"][height="235"], object[width="180"][height="250"], object[width="180"][height="300"], object[width="180"][height="540"], object[width="185"][height="228"], object[width="188"][height="290"], object[width="190"][height="310"], object[width="190"][height="46"], object[width="190"][height="700"], object[width="200"][height="100"], object[width="200"][height="150"], object[width="200"][height="220"], object[width="200"][height="300"] {
            display: none !important;
        }

        object[width="200"][height="352"], object[width="200"][height="360"], object[width="200"][height="400"], object[width="210"][height="300"], object[width="215"][height="400"], object[width="220"][height="160"], object[width="220"][height="320"], object[width="224"][height="373"], object[width="229"][height="229"], object[width="230"][height="100"], object[width="230"][height="60"], object[width="234"][height="60"], object[width="240"][height="100"], object[width="240"][height="120"], object[width="240"][height="200"], object[width="240"][height="240"], object[width="240"][height="300"], object[width="240"][height="325"], object[width="240"][height="350"], object[width="240"][height="400"], object[width="240"][height="800"], object[width="250"][height="125"], object[width="250"][height="250"], object[width="250"][height="500"], object[width="250"][height="520"], object[width="250"][height="60"], object[width="256"][height="300"], object[width="260"][height="450"], object[width="265"][height="300"], object[width="270"][height="540"], object[width="275"][height="138"], object[width="280"][height="90"], object[width="300"][height="250"], object[width="300"][height="276"], object[width="300"][height="78"], object[width="340"][height="170"], object[width="340"][height="585"], object[width="340"][height="80"], object[width="350"][height="115"], object[width="350"][height="170"], object[width="360"][height="120"], object[width="360"][height="60"], object[width="370"][height="170"], object[width="400"][height="50"], object[width="400"][height="87"], object[width="408"][height="275"], object[width="440"][height="100"], object[width="460"][height="40"], object[width="468"][height="40"], object[width="468"][height="60"] {
            display: none !important;
        }

        object[width="468"][height="90"], object[width="469"][height="70"], object[width="470"][height="50"], object[width="480"][height="100"], object[width="480"][height="60"], object[width="500"][height="100"], object[width="500"][height="200"], object[width="500"][height="250"], object[width="500"][height="78"], object[width="530"][height="170"], object[width="545"][height="70"], object[width="550"][height="130"], object[width="550"][height="200"], object[width="560"][height="120"], object[width="570"][height="180"], object[width="572"][height="106"], object[width="580"][height="80"], object[width="590"][height="100"], object[width="600"][height="130"], object[width="600"][height="200"], object[width="600"][height="250"], object[width="600"][height="80"], object[width="600"][height="90"], object[width="610"][height="130"], object[width="620"][height="120"], object[width="626"][height="75"], object[width="630"][height="206"], object[width="635"][height="185"], object[width="675"][height="80"], object[width="680"][height="125"], object[width="680"][height="240"], object[width="680"][height="90"], object[width="690"][height="85"], object[width="700"][height="100"], object[width="700"][height="87"], object[width="700"][height="90"], object[width="703"][height="120"], object[width="720"][height="120"], object[width="720"][height="60"], object[width="720"][height="90"], object[width="728"][height="90"], object[width="738"][height="90"], object[width="750"][height="100"], object[width="758"][height="93"], object[width="760"][height="90"], object[width="770"][height="100"], object[width="800"][height="128"], object[width="800"][height="200"], object[width="800"][height="90"], object[width="850"][height="100"] {
            display: none !important;
        }

        object[width="850"][height="83"], object[width="880"][height="80"], object[width="900"][height="100"], object[width="900"][height="150"], object[width="900"][height="68"], object[width="900"][height="90"], object[width="940"][height="120"], object[width="950"][height="150"], object[width="950"][height="90"], object[width="951"][height="90"], object[width="980"][height="100"], object[width="980"][height="250"], object[width="982"][height="150"], object[width="990"][height="206"], #__BULLETIN__bdiv[style="position"], .ad-container--leaderboard, #videopageadblock, #floatingAdContainer, .ad_w300i, .ad-300, .commercial-unit-mobile-bottom, .mobile-instream-ad-holder-single, #ad_wp_base, #adxtop, #ad_728h, #ad_336_singlebt, .tjads, topadblock, #ad-fullbanner2-billboard-outer, .loop_google_ad, .amp_ad_wrapper, .commercial-unit-mobile-top, div[id*="ScriptRootN"], .ad-engage, #gads_middle, .add_300x250, .ContentAd, a[href^="https://join3.bannedsextapes.com/track/"], .puFloatLine > #puFloatDiv, a[href*=".ufinkln.com/"], body > #overover[style="position:fixed;width:100%;height:100%;background:silver;z-index: 2;opacity: 0.1;"], body > #overover[style="position:fixed;width:100%;height:100%;background:silver;z-index: 2;opacity: 0.1;"] ~ #obrazek, .stripper > a[href*="istripper"] > img, a[href*="/fdh/wth.php?"], .BetterJsPopOverlay, .videojs-hero-overlay, .wpcnt > .wpa, #BannerBox, #ad-topper, #ad_300X250 {
            display: none !important;
        }


        a[href*="cpaggetti.ru"], a[href*="cpamatica.com"], a[href*="direct"][href*="advert.ru"], a[href*="download-center.club"], a[href*="globalteaser.ru"], a[href*="incrypted.net"][href*="banner"][target="_blank"], a[href*="installoffer.net"], a[href*="leadadvert.ru"], a[href*="lenkmio.com"][target="_blank"], a[href*="lentainform.com/pnews/"], a[href*="marathonmirrorbet.com"], a[href*="medicinetizer.ru"], a[href*="news-network.ru"][target="_blank"], a[href*="newsnetwork.ru"][target="_blank"], a[href*="novostimira.biz"], a[href*="omnicpa.ru"], a[href*="onetwoaffiliates.com"], a[href*="people-group.su"], a[href*="promoheads.com"], a[href*="reals-gooods.ru"], a[href*="recreativ.ru"], a[href*="redtram.com"], a[href*="rootmedia.cc"], a[href*="runetki.com"], a[href*="salesdoubler.com.ua"], a[href*="teasermoney.com"], a[href*="tizerclick.com"], a[href*="tovar.helloprice.ru/click/"], a[href*="trafmag.com"], a[href*="true-gooods.ru"], a[href*="universallnk.com"], a[href*="www.nnn.ru"], a[href*="wwwapteka.info"], a[href*="zen.yandex."] > img:not([src*="gstatic.com"]):not([onload*="google"]):not([jsaction]), a[href^="http://amigo-free.website/"], a[href^="http://amigo-source.website/"], a[href^="http://amigoman.pw/"], a[href^="http://amigone.pw/"], a[href^="https://bither.one/"], a[onclick*="media-rotate.com"], a[onclick*="reklamka.ru.net"], div[class*="notifier_baloon_"], div[id$="notifiers_wrap"], div[id^="vk_ads_"], form[action^="//12go.asia/"][target="_blank"] > .powered, iframe[src*="//sass.com.ua/"], iframe[src*="/adnetpartner.com"], iframe[src*="/uniontraff.com"], iframe[src*="bongacams.com"], iframe[src*="directadvert"] {
            display: none !important;
        }

        iframe[src^="https://www.favorit.com.ua/"], iframe[width="240"][height="400"], noindex a[href^="http://www.westmister.eu/collection/"], noindex a[href^="http://www.westmister.eu/collection/"] ~ *, a[href*="://smi2.ru/newdata/news?ad="], a[href*="://smi2.ru/newdata/news?ad="] *, embed[width="640"][height="160"], iframe[width="100%"][height="60"], iframe[width="240"][height="300"], img[width="240"][height="400"], object[width="1000"][height="250"], object[width="1000"][height="270"], object[width="200"][height="200"], object[width="260"][height="130"], object[width="300"][height="60"], object[width="640"][height="100"], object[width="640"][height="160"], a[href^="https://redirect.ero-advertising.com"] > img, a[href*="://kingandqueenpro.com/r/?"], #ads_iframe, #adv, #advblock, .madv, .td-a-rec, div[class*="td-a-rec-id-"], img[width="468"][height="60"], img[width="728"][height="90"], iframe[width="100%"][height="120"], iframe[width="200"][height="240"], iframe[width="240"][height="400"], iframe[width="300"][height="250"], iframe[width="600"][height="90"], iframe[width="728"][height="90"], img[width="240px"][height="400px"], object[width="100%"][height="300"], object[width="300"][height="300"], .adsbygoogle, .b_ad, .b-header-banner, .banners_block, .post-ads, .top-banners, div[id^="google_ads_iframe_"], #AD-300x250, #AD_CONTROL_28, #AD_Top, #AD_banner, #AdColumn, #AdContainer, #AdHeader, #AdImage {
            display: none !important;
        }

        a[href^="http://online.ladbrokes.com/promoRedirect?"], a[href^="http://partner.sbaffiliates.com/"], a[href^="http://pubads.g.doubleclick.net/"], a[href^="http://us.marketgid.com"], a[href^="http://websitedhoome.com/"], a[href^="http://www.adskeeper.co.uk/"], a[href^="http://www.fbooksluts.com/"], a[href^="http://www.fleshlight.com/"], a[href^="http://www.liutilities.com/"], a[href^="http://www.mrskin.com/tour"], a[href^="http://www.socialsex.com/"], a[href^="http://www.yourfuckbook.com/?"], a[href^="https://ad.doubleclick.net/"], a[href^="https://badoinkvr.com/"], a[href^="https://servedbyadbutler.com/"], a[href^="https://www.financeads.net/tc.php?"], a[href^="https://www.moscarossa.biz/"], a[href^="https://www.mrskin.com/tour"], div[data-native_ad], div[id^="adfox_"], div[id^="advads-"], div[id^="crt-"][style], div[id^="dfp-ad-"], div[id^="div-gpt-ad"], div[itemtype="http://schema.org/WPAdBlock"], iframe[id^="google_ads_frame"], iframe[id^="google_ads_iframe"], iframe[src^="http://ad.yieldmanager.com/"], [id*="ScriptRoot"], input[onclick^="window.open('http://www.FriendlyDuck.com/"], a[href*=".trust.zone"], #rc-row-container, .rc-item-wrapper, AMP-AD, .ddb, a[onmousedown^="this.href='https://paid.outbrain.com/network/redir?"][target="_blank"], .taboola-ad, .trc_rbox .syndicatedItem, .trc_rbox_border_elm .syndicatedItem, .trc_rbox_div .syndicatedItem, .trc_related_container div[data-item-syndicated="true"], .adsbox {
            display: none !important;
        }
    </style>

<body>
<div>
    <div class="error-head">
        <#--<img src="${rc.getContextPath()}/gif/abc.gif" alt="BulSchool">-->
        <span>Видеокурсы по программированию</span>
    </div>
</div>
<div>
    <div class="error-main-bg"></div>
</div>
<div>
    <div class="error-footer">
        <span>Ошибка</span>
        <p>Извините, произошла ошибка</p>
        <a href="${rc.getContextPath()}/index">на главную</a>
    </div>
</div>


<div class="mallbery-caa" style="z-index: 2147483647 !important; text-transform: none !important; position: fixed;">

</div>
</body>
</html>